name: L0

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          path: tdd-template

      - name: Install valgrind, coverage, cmake
        run: |
          sudo apt update
          sudo apt install -y valgrind lcov cmake

      - name: Configure
        working-directory: ${{github.workspace}}
        run: cmake -S tdd-template/L0 -B build/l0test -DCMAKE_INSTALL_PREFIX="install/usr" -DCMAKE_CXX_FLAGS="--coverage -Wall -Werror"

      - name: Build
        working-directory: ${{github.workspace}}
        run: cmake --build build/l0test --target install

      - name: Run
        working-directory: ${{github.workspace}}
        run: PATH=${PWD}/install/usr/bin:${PATH} LD_LIBRARY_PATH=${PWD}/install/usr/lib:${LD_LIBRARY_PATH} valgrind --tool=memcheck --log-file=valgrind_log --leak-check=yes --show-reachable=yes --track-fds=yes --fair-sched=try l0test

      - name: Generate coverage
        working-directory: ${{github.workspace}}
        run: |
          lcov -c -o coverage.info -d build/l0test
          genhtml -o coverage coverage.info

      - name: Upload artifacts
        if: ${{ !env.ACT }}
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: |
            coverage/
            valgrind_log
          if-no-files-found: warn
